/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('@/src/components/Header/index.vue')['default']
    Layout: typeof import('@/src/components/Layout/index.vue')['default']
    SmsCode: typeof import('@/src/components/SmsCode/index.vue')['default']
  }
}
